name: 'General Card Config'
description: 'Overrides for Paragraph types that were installed by other modules like Bootstrap.'
type: module
core: 8.x
dependencies:
  - block
  - contact
  - entity_reference_revisions
  - field
  - file
  - image
  - link
  - options
  - paragraphs
  - text
  - views
  - viewsreference
version: 8.x
package: d8m
