name: 'Colorado Division of Homeland Security and Emergency Management'
mail: no-reply@www.colorado.gov
slogan: ''
page:
  403: ''
  404: ''
  front: /node/78
admin_compact_mode: false
weight_select_max: 100
langcode: en
default_langcode: en
_core:
  default_config_hash: MN59cq0iWvVh5EMGJpZZQD0utSmkIeO_dDtqzeI20ZU
uuid: c7d57e0e-5172-4247-acff-130f37b56d47
