<?php

/**
 * Implements hook_page_attachments().
 */
function ci_admin_tweaks_page_attachments(array &$attachments) {
    $attachments['#attached']['library'][] = 'ci_admin_tweaks/admin-tweaks';
}

function ci_admin_tweaks_theme($existing, $type, $theme, $path) {
    return [
        'page__node__edit' => [
            'templates' => 'page--node--edit',
            'base hook' => 'node',
        ],
    ];
}

use Drupal\Core\Entity\ContentEntityInterface;
use Drupal\field\Entity\FieldStorageConfig;

/**
 * Set dynamic allowed values for the alignment field.
 *
 * @param \Drupal\field\Entity\FieldStorageConfig $definition
 *   The field definition.
 * @param \Drupal\Core\Entity\ContentEntityInterface|null $entity
 *   The entity being created if applicable.
 * @param bool $cacheable
 *   Boolean indicating if the results are cacheable.
 *
 * @return array
 *   An array of possible key and value options.
 *
 * @see options_allowed_values()
 */
function ci_admin_tweaks_allowed_values_function(FieldStorageConfig $definition, ContentEntityInterface $entity = NULL, $cacheable) {
  $options = [
    'Show Site Background Image' => 'Show Site Background Image',
    'Show Site Background Color' => 'Show Site Background Color',


  ];
  // Add a custom alignment option for Article nodes.
  if ($entity->bundle() == 'landing_page') {
    $options['Show Custom Background Image'] = 'Show Custom Background Image';
  }

  if ($entity->bundle() == 'landing_page') {

    $options['Show Custom Background Color'] = 'Show Custom Background Color';
  }

  return $options;
}