<?php

/**
 * Implements hook_page_attachments().
 */
function ci_layouts_page_attachments(array &$attachments) {
    $attachments['#attached']['library'][] = 'ci_admin_tweaks/admin-tweaks';
    $attachments['#attached']['library'][] = 'ci_layouts/ci_layouts';
}

function ci_layouts_theme($existing, $type, $theme, $path) {
    return [
        'page__admin__content__layouts' => [
            'templates' => 'page--admin--content--layouts',
            'base hook' => 'node',
        ],
    ];
}
