<?php

$databases = array();
$config_directories = array();
$settings['hash_salt'] = 'NONE';
$settings['file_scan_ignore_directories'] = [
  'node_modules',
  'bower_components',
];

if (isset($_ENV["AH_PRODUCTION"]) && $_ENV["AH_PRODUCTION"] == 1) {

  $config['system.performance']['css']['preprocess'] = TRUE;
  $config['system.performance']['js']['preprocess'] = TRUE;
} else {
  $config['system.logging']['error_level'] = 'verbose';
  $config['system.performance']['css']['preprocess'] = FALSE;
  $config['system.performance']['js']['preprocess'] = FALSE;
  $settings['update_free_access'] = TRUE;

}

if (isset($_ENV["AH_SITE_ENVIRONMENT"])) {
  if (file_exists('/var/www/site-php')) {
    require '/var/www/site-php/coloradod8m/ag-settings.inc';
  }
}

$config_directories['sync'] = '../config/synchronize/sync'; $config_directories['post-sync'] = '../config/synchronize/post-sync';
$config_directories['staging'] = '../config/synchronize/staging';
$config_directories['sole'] = '../config/ag.colorado.gov/sole';
$settings['install_profile'] = 'ci_start';
$config['content_directory'] = '../content';

$settings['file_temporary_path'] = 'tmp';
$config['system.site']['name'] = 'Department of Agriculture';
// <DDSETTINGS>
// Please don't edit anything between <DDSETTINGS> tags.
// This section is autogenerated by Acquia Dev Desktop.
if (isset($_SERVER['DEVDESKTOP_DRUPAL_SETTINGS_DIR']) && file_exists($_SERVER['DEVDESKTOP_DRUPAL_SETTINGS_DIR'] . '/cld_prod_coloradod8m_dev_ag_colorado_gov.inc')) {
  require $_SERVER['DEVDESKTOP_DRUPAL_SETTINGS_DIR'] . '/cld_prod_coloradod8m_dev_ag_colorado_gov.inc';
}

$settings['memcache']['stampede_protection'] = TRUE;

$acquia_search_environment_mapping = [

  // EDIT: Add all environments below
  // syntax is:   "value of $_ENV[AH_SITE_ENVIRONMENT]" => "core ID"
  "prod" => "CDIY-145117",
  "test" => "CDIY-145117.test.default",
  "dev" => "CDIY-145117.dev.default",

  // EDIT: Fallback Core ID for other environments (or local environments)
  "FALLBACK" => "CDIY-145117.dev.default",
];

$searchapi_server_ids = [ "acquia_search" ];

// EDIT below to contain the apachesolr.module environment IDs to override.
// (Only needed if using D7 acquia_search.module)
$apachesolr_environment_ids = [ "acquia_search_server_1" ];

/**
 * DO NOT EDIT BELOW THIS LINE =================================================
 */

$settings['memcache']['stampede_protection'] = TRUE;
$config['image.settings']['allow_insecure_derivatives'] = TRUE;