<?php

/**
 * @file
 * Hook implementations for the sharethis_block module.
 */

/**
 * Implements hook_library_info_alter().
 */
function sharethis_block_library_info_alter(&$libraries, $extension) {
  if (($extension == 'sharethis_block') && isset($libraries['sharethis'])) {
    $config = \Drupal::config('sharethis_block.configuration');
    // Get the property ID.
    $property_id = $config->get('sharethis_property');
    // Determine the product type from the configuration.
    $product_type = $config->get('sharethis_inline') ? 'inline-share-buttons' : 'sticky-share-button';
    $remote = str_replace('PROPERTYID', $property_id, $libraries['sharethis']['remote']);
    $remote = str_replace('PRODUCT_TYPE', $product_type, $remote);
    $libraries['sharethis']['remote'] = $remote;
    $options = reset($libraries['sharethis']['js']);
    $libraries['sharethis']['js'] = [
      $libraries['sharethis']['remote'] => $options,
    ];
  }
}

/**
 * Implements hook_theme().
 */
function sharethis_block_theme() {
  return [
    'block__sharethis' => [
      'base hook' => 'block',
    ],
  ];
}
