roleassign_roles:
  user_administrator: user_administrator
  administrator: '0'
  support_administrator: '0'
  content_administrator: '0'
  content_publisher: '0'
  content_editor: '0'
  structure_administrator: '0'
  structure_editor: '0'
_core:
  default_config_hash: iKucdYPrf1EPMz6Y3s71EADiRcAiwoLTIw9_JoxH-Jg
