name: 'Block Visibility Config'
type: module
core: 8.x
dependencies:
  - block
  - block_class
  - block_content
  - block_visibility_groups
  - calendar
  - ci_ct_content_types
  - ci_ct_event
  - ci_search
  - ci_views_config
  - ctools
  - entity_reference_revisions
  - help
  - masquerade
  - menu_block
  - menu_condition
  - node
  - paragraphs
  - search_api
  - search_api_db
  - sharethis_block
  - superfish
  - system
  - taxonomy
  - term_condition
  - text
  - user
  - views
package: 'Colorado Interactive'
