name: 'Block Visibility Config'
type: module
core: 8.x
dependencies:
  - block
  - block_class
  - block_content
  - block_visibility_groups
  - ctools
  - help
  - masquerade
  - menu_block
  - menu_condition
  - search
  - system
  - term_condition
  - user
package: 'Colorado Interactive'
