cdn_provider: ''
_core:
  default_config_hash: TxwSU0jOgBK6531PJDhvWiqDs4t5WpV1YylSMi-vpGc
favicon:
  mimetype: image/vnd.microsoft.icon
  path:
  url: themes/ci_xy/favicon.ico
  use_default: 1
schemas:
  bootstrap: 8000
  ci_xy: 8000
features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: 1
  node_user_picture: true
logo:
  path: themes/ci_xy/coloradogov-logo.svg
  url: ''
  use_default: 0
region_wells:
  branding: ''
  global_header: ''
  search: ''
  jumbotron: ''
  navigation: ''
  navigation_collapsible: ''
  header: ''
  highlighted: ''
  help: ''
  content: ''
  sidebar_first: ''
  sidebar_second: ''
  footer: ''
  global_footer: ''
  block_reserve: ''
table_responsive: '-1'
table: ''
breadcrumb_home: 1
