roleassign_roles:
  user_administrator: user_administrator
  content_administrator: content_administrator
  content_publisher: content_publisher
  content_editor: content_editor
  structure_administrator: structure_administrator
  administrator: '0'
  support_administrator: '0'
_core:
  default_config_hash: iKucdYPrf1EPMz6Y3s71EADiRcAiwoLTIw9_JoxH-Jg
