name: 'CI Drupal 8'
mail: no-reply@www.colorado.gov
slogan: ''
page:
  403: ''
  404: ''
  front: /node/1
admin_compact_mode: false
weight_select_max: 100
langcode: en
default_langcode: en
_core:
  default_config_hash: MN59cq0iWvVh5EMGJpZZQD0utSmkIeO_dDtqzeI20ZU
uuid: 16c2087b-d919-4eba-b614-20406e1e27f7
