bundle: ci_cr
required:
  - core.entity_form_display.block_content.basic.default
  - core.entity_form_display.paragraph.bp_accordion.default
  - core.entity_form_display.paragraph.bp_accordion_section.default
  - core.entity_form_display.paragraph.bp_blank.default
  - core.entity_form_display.paragraph.bp_block.default
  - core.entity_form_display.paragraph.bp_carousel.default
  - core.entity_form_display.paragraph.bp_columns.default
  - core.entity_form_display.paragraph.bp_columns_three_uneven.default
  - core.entity_form_display.paragraph.bp_columns_two_uneven.default
  - core.entity_form_display.paragraph.bp_contact.default
  - core.entity_form_display.paragraph.bp_image.default
  - core.entity_form_display.paragraph.bp_modal.default
  - core.entity_form_display.paragraph.bp_simple.default
  - core.entity_form_display.paragraph.bp_tabs.default
  - core.entity_form_display.paragraph.bp_tab_section.default
  - core.entity_form_display.paragraph.bp_view.default
  - core.entity_view_display.block_content.basic.default
  - field.field.block_content.basic.field_paragraphs
  - field.field.paragraph.bp_accordion.bp_accordion_section
  - field.field.paragraph.bp_accordion.bp_background
  - field.field.paragraph.bp_accordion.bp_width
  - field.field.paragraph.bp_accordion_section.bp_accordion_section_body
  - field.field.paragraph.bp_accordion_section.bp_accordion_section_title
  - field.field.paragraph.bp_blank.bp_background
  - field.field.paragraph.bp_blank.bp_unrestricted
  - field.field.paragraph.bp_blank.bp_width
  - field.field.paragraph.bp_block.bp_background
  - field.field.paragraph.bp_block.bp_block
  - field.field.paragraph.bp_block.bp_width
  - field.field.paragraph.bp_carousel.bp_background
  - field.field.paragraph.bp_carousel.bp_slide_content
  - field.field.paragraph.bp_carousel.bp_slide_interval
  - field.field.paragraph.bp_carousel.bp_width
  - field.field.paragraph.bp_columns.bp_background
  - field.field.paragraph.bp_columns.bp_column_content
  - field.field.paragraph.bp_columns.bp_width
  - field.field.paragraph.bp_columns_three_uneven.bp_background
  - field.field.paragraph.bp_columns_three_uneven.bp_column_content_3
  - field.field.paragraph.bp_columns_three_uneven.bp_column_style_3
  - field.field.paragraph.bp_columns_three_uneven.bp_width
  - field.field.paragraph.bp_columns_two_uneven.bp_background
  - field.field.paragraph.bp_columns_two_uneven.bp_column_content_2
  - field.field.paragraph.bp_columns_two_uneven.bp_column_style_2
  - field.field.paragraph.bp_columns_two_uneven.bp_width
  - field.field.paragraph.bp_contact.bp_background
  - field.field.paragraph.bp_contact.bp_contact
  - field.field.paragraph.bp_contact.bp_width
  - field.field.paragraph.bp_image.bp_background
  - field.field.paragraph.bp_image.bp_image_field
  - field.field.paragraph.bp_image.bp_link
  - field.field.paragraph.bp_image.bp_width
  - field.field.paragraph.bp_modal.bp_background
  - field.field.paragraph.bp_modal.bp_modal_body
  - field.field.paragraph.bp_modal.bp_modal_button_text
  - field.field.paragraph.bp_modal.bp_modal_footer
  - field.field.paragraph.bp_modal.bp_modal_title
  - field.field.paragraph.bp_modal.bp_width
  - field.field.paragraph.bp_simple.bp_background
  - field.field.paragraph.bp_simple.bp_text
  - field.field.paragraph.bp_simple.bp_width
  - field.field.paragraph.bp_tabs.bp_background
  - field.field.paragraph.bp_tabs.bp_tab_section
  - field.field.paragraph.bp_tabs.bp_width
  - field.field.paragraph.bp_tab_section.bp_tab_section_body
  - field.field.paragraph.bp_tab_section.bp_tab_section_title
  - field.field.paragraph.bp_view.bp_background
  - field.field.paragraph.bp_view.bp_view
  - field.field.paragraph.bp_view.bp_width
  - field.storage.paragraph.bp_accordion_section
  - field.storage.paragraph.bp_accordion_section_body
  - field.storage.paragraph.bp_accordion_section_title
  - field.storage.paragraph.bp_background
  - field.storage.paragraph.bp_block
  - field.storage.paragraph.bp_column_content
  - field.storage.paragraph.bp_column_content_2
  - field.storage.paragraph.bp_column_content_3
  - field.storage.paragraph.bp_column_style_2
  - field.storage.paragraph.bp_column_style_3
  - field.storage.paragraph.bp_contact
  - field.storage.paragraph.bp_image_field
  - field.storage.paragraph.bp_link
  - field.storage.paragraph.bp_modal_body
  - field.storage.paragraph.bp_modal_button_text
  - field.storage.paragraph.bp_modal_footer
  - field.storage.paragraph.bp_modal_title
  - field.storage.paragraph.bp_slide_content
  - field.storage.paragraph.bp_slide_interval
  - field.storage.paragraph.bp_tab_section
  - field.storage.paragraph.bp_tab_section_body
  - field.storage.paragraph.bp_tab_section_title
  - field.storage.paragraph.bp_text
  - field.storage.paragraph.bp_unrestricted
  - field.storage.paragraph.bp_view
  - field.storage.paragraph.bp_width
  - field.storage.paragraph.field_layout_style
  - paragraphs.paragraphs_type.bp_accordion
  - paragraphs.paragraphs_type.bp_accordion_section
  - paragraphs.paragraphs_type.bp_blank
  - paragraphs.paragraphs_type.bp_block
  - paragraphs.paragraphs_type.bp_carousel
  - paragraphs.paragraphs_type.bp_columns
  - paragraphs.paragraphs_type.bp_columns_three_uneven
  - paragraphs.paragraphs_type.bp_columns_two_uneven
  - paragraphs.paragraphs_type.bp_contact
  - paragraphs.paragraphs_type.bp_image
  - paragraphs.paragraphs_type.bp_modal
  - paragraphs.paragraphs_type.bp_simple
  - paragraphs.paragraphs_type.bp_tabs
  - paragraphs.paragraphs_type.bp_tab_section
  - paragraphs.paragraphs_type.bp_view
