<?php

/**
 * @file
 * simple.module
 */

/**
 * Implements hook_menu().
 */
function simple_menu() {
  $items = array();
  return $items;
}
$config = \Drupal::config('system.site')->get('slogan');

/**
 * Implements hook_form_alter().
 */
function simple_form_alter() {

}
function simple_preprocess_page(&$variables) {

    $variables['cta_bar'] = ['#markup' => '<h2>Test CTA Bar</h2>'];
    $variables['email'] = \Drupal::config('simple.settings')->get('simple.email');

}
