<?php

/**
 * @file
 * ci_form_tweaks.module
 */

/**
 * Implements hook_menu().
 */
function ci_form_tweaks_menu() {
  $items = array();
  return $items;
}

/**
 * Implements hook_form_alter().
 */
function ci_form_tweaks_form_alter() {

}

function ci_form_tweaks_theme() {
	   $theme['ci_form_tweaks_page_theme'] = array(
	     'variables' => array('number' => NULL),
	     'template' => 'shedow-theme-page',
	   );
	   return $theme;
	}
  
  function ci_form_tweaks_preprocess_node_edit_form(&$variables) {
    $variables['#attached']['library'][] = 'ci_form_tweaks/ci_form_tweaks';
  }
  