<?php

# Theme Color Options
$form['type_options'] = array(
    '#type' => 'value',
    '#value' => array('color__brand-slate--strong' => t('Brand Colorado Slate'),
        'color__brand-green--strong' => t('Brand Colorado Green'),
        'color__brand-silver--strong' => t('Brand Colorado Silver'),
        'color__brand-orange--strong' => t('Brand Colorado Orange'),
        'color__brand-brown--strong' => t('Brand Colorado Brown'),
        'color__brand-blue--strong' => t('Brand Colorado Blue'),
        'color__black--strong' => t('Brand Colorado Black'),
        'color__evening--strong' => t('Brand Colorado Evening'),
        'color__charcoal--strong' => t('Brand Colorado Charcoal'),
        'color__blackboard--strong' => t('Brand Colorado Blackboard'),
        'color__grey-sand--strong' => t('Brand Colorado Grey Sand'),
        'color__sleek-grey--strong' => t('Brand Colorado Sleek Grey'),
        'color__lemon-grass--strong' => t('Brand Colorado Lemon Grass'),
        'color__walnut--strong' => t('Brand Colorado Walnut'),
        'color__beige--strong' => t('Brand Colorado Beige'),
        'color__spice--strong' => t('Brand Colorado Spice'),
        'color__brick-red--strong' => t('Brand Colorado Brick Red'),
        'color__scarlet--strong' => t('Brand Colorado Scarlet'),
        'color__cognac--strong' => t('Brand Colorado Cognac'),
        'color__tiger-orange--strong' => t('Brand Colorado Tiger Orange'),
        'color__tiger-wheat--strong' => t('Brand Colorado Wheat'),
        'color__sunflower--strong' => t('Brand Colorado Sunflower'),
        'color__lemon--strong' => t('Brand Colorado Lemon'),
        'color__eggplant--strong' => t('Brand Colorado Eggplant'),
        'color__grape--strong' => t('Brand Colorado Grape'),
        'color__ink--strong' => t('Brand Colorado Ink'),
        'color__sky-blue--strong' => t('Brand Colorado Sky Blue'),
        'color__pacific-blue--strong' => t('Brand Colorado Pacific Blue'),
        'color__aqua--strong' => t('Brand Colorado Aqua'),
        'color__pastel-blue--strong' => t('Brand Colorado Pastel Blue'),
        'color__ice--strong' => t('Brand Colorado Ice'),
        'color__forest--strong' => t('Brand Colorado Forest'),
        'color__forest--strong' => t('Brand Colorado Forest'),
        'color__neon-green--strong' => t('Brand Colorado Neon Green'),
        'color__cucumber--strong' => t('Brand Colorado Cucumber'),
        'color__fern--strong' => t('Brand Colorado Fern'),
        'color__mineral-green--strong' => t('Brand Colorado Mineral Green'),
        'color__pine-needle--strong' => t('Brand Colorado Pine Needle'),
        'color__corduroy--strong' => t('Brand Colorado Corduroy'),
        'color__sea-foam--strong' => t('Brand Colorado Sea Foam'))
);