<?php

# Theme Color Options
$form['type_options'] = array(
    '#type' => 'value',
    '#value' => array('' => t('Default'),
        'color__brand-green--strong' => t('Brand Colorado Green'),
        'color__brand-slate--strong' => t('Brand Colorado Slate'),
        'color__brand-silver--strong' => t('Brand Colorado Silver'),
        'color__brand-orange--strong' => t('Brand Colorado Orange'),
        'color__brand-brown--strong' => t('Brand Colorado Brown'),
        'color__brand-blue--strong' => t('Brand Colorado Blue'),
        'color__black--strong' => t('Black'),
        'color__evening--strong' => t('Evening'),
        'color__charcoal--strong' => t('Charcoal'),
        'color__blackboard--strong' => t('Blackboard'),
        'color__grey-sand--strong' => t('Grey Sand'),
        'color__sleek-grey--strong' => t('Sleek Grey'),
        'color__lemon-grass--strong' => t('Lemon Grass'),
        'color__walnut--strong' => t('Walnut'),
        'color__beige--strong' => t('Beige'),
        'color__spice--strong' => t('Spice'),
        'color__brick-red--strong' => t('Brick Red'),
        'color__scarlet--strong' => t('Scarlet'),
        'color__cognac--strong' => t('Cognac'),
        'color__tiger-orange--strong' => t('Tiger Orange'),
        'color__wheat--strong' => t('Wheat'),
        'color__sunflower--strong' => t('Sunflower'),
        'color__lemon--strong' => t('Lemon'),
        'color__eggplant--strong' => t('Eggplant'),
        'color__grape--strong' => t('Grape'),
        'color__ink--strong' => t('Ink'),
        'color__sky-blue--strong' => t('Sky Blue'),
        'color__pacific-blue--strong' => t('Pacific Blue'),
        'color__aqua--strong' => t('Aqua'),
        'color__pastel-blue--strong' => t('Pastel Blue'),
        'color__ice--strong' => t('Ice'),
        'color__forest--strong' => t('Forest'),
        'color__neon-green--strong' => t('Neon Green'),
        'color__cucumber--strong' => t('Cucumber'),
        'color__fern--strong' => t('Fern'),
        'color__mineral-green--strong' => t('Mineral Green'),
        'color__pine-needle--strong' => t('Pine Needle'),
        'color__corduroy--strong' => t('Corduroy'),
        'color__sea-foam--strong' => t('Sea Foam'))
);