name: ckeditor_config
description: 'CI''s configuration of the CKEditor.'
type: module
core: 8.x
dependencies:
  - ckeditor
  - crop
  - editor
  - editor_file
  - entity_embed
  - file
  - filter
  - image
  - node
  - video_embed_wysiwyg
package: 'Colorado Interactive'
version: 8.x
