name: ckeditor_config
description: 'CI''s configuration of the CKEditor.'
type: module
core: 8.x
dependencies:
  - ckeditor
  - crop
  - editor
  - entity_embed
  - filter
  - linkit
  - video_embed_wysiwyg
version: 8.x
